### ISSUE TITLE
Rule suggestion: warning/error on unnecessary files

### ISSUE THREAD

**Issue by alebelcor** [sindresorhus/npmlint#2]
I often see packages installed that carry around `test` folders, dotfiles and other things needed when developing such package but not so much when installing it and using it.

I think a rule that checks a combination of `files` and `bin` in `package.json` and `.npmignore` (I may be forgetting something) would be useful.

This project is exciting. Thank you!

**Comment by Kikobeats** [comment]
About the warning message, you can check a similar approach in a similar project:

https://github.com/Kikobeats/finepack

**Comment by sindresorhus** [comment]
:+1: As commented in https://github.com/sindresorhus/npmlint/issues/3, I already have a huge list of ideas of rules. Just need to clean it up first. This is one of them.

**Comment by alebelcor** [comment]
Sweet! I'll close this then.

**Comment by sindresorhus** [comment]
Can keep it open. It's something I want.
