### ISSUE TITLE
TODO list?

### ISSUE THREAD

**Issue by hemanth** [sindresorhus/npmlint#3]
Hey! 

I noticed it's WIP, do you a TODO list in mind for this?

Looking forwards to contribute and use it with [npm-janitor](https://www.npmjs.com/package/npm-janitor) :+1:

**Comment by sindresorhus** [comment]
I open sourced it as it's been lying dormant for 2 years in my `~/dev` folder and wanted to show it to someone. I have a gigantic todo list over things it could do, but will need to clean it up first.

**Comment by hemanth** [comment]
Cool, waiting to see them, thanks.
